services:
  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - 6500:5432
    env_file:
      - ./app.env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - common

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: rblbl@mail.ru
      PGADMIN_DEFAULT_PASSWORD: s0m30n3
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - common

  go-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_service
    command: >
      sh -c "sleep 5 &&
             /app/main"
    ports:
      - "8888:8888"
    env_file:
      - ./app.env
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: golang-gorm
      POSTGRES_PORT: 5432
    depends_on:
      - postgres
    networks:
      - common

volumes:
  postgres:

networks:
  common: