services:

  imgproxy:
    image: darthsim/imgproxy@sha256:c1250eeb8efb8b3946e9393f4b1e2871cf15e74e3a546e4110568c147b1a8628
    container_name: imgproxy
    ports:
      - "50200:8000"
    env_file:
      - ./app.env
    environment:
      PORT: 8000
    networks:
      - backend
      - s3_minio

  go-service:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_service
    command: >
      sh -c "sleep 5 &&
             /app/main"
    env_file:
      - ./app.env
    environment:
      GIN_PORT: 8888
      GIN_MODE: debug
      CASBIN_MODEL_PATH: /etc/casbin/model.conf
      CASBIN_POLICY_PATH: /etc/casbin/policy.csv
    volumes:
      - ./casbin:/etc/casbin
    networks:
      - backend

  nginx:
    platform: linux/amd64
    image: nginx:latest
    container_name: nginx
    ports:
      - "8843:443"
      - "8899:80"
    environment:
      FRONTEND_URL: ${FRONTEND_URL:-http://31.129.107.103:4200}
      BACKEND_URL: ${BACKEND_URL:-http://go_service:8888} # go_service PORT value
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./docs/openapi_v3.yaml:/var/www/openapi_v3.yaml:ro
    depends_on:
      - go-service
    networks:
      - backend

networks:
  backend:
    external: true
  s3_minio:
    external: true