version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 6500:5432
    env_file:
      - ./app.env
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: rblbl@mail.ru
      PGADMIN_DEFAULT_PASSWORD: s0m30n3
    ports:
      - "8080:80"
    depends_on:
      - postgres

#  go-service:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: go_service
#    ports:
#      - "8081:8081"  # Change this if your Go service exposes a different port
#    env_file:
#      - ./app.env
#    depends_on:
#      - postgres

volumes:
  postgres:
