services:

  go-service:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_service
    command: >
      sh -c "sleep 5 &&
             /app/main"
    env_file:
      - ./app.env
    networks:
      - backend

  nginx:
    platform: linux/amd64
    image: nginx:latest
    container_name: nginx
    ports:
      - "8843:443"
      - "8899:80"
    environment:
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:4200}
      BACKEND_URL: ${BACKEND_URL:-http://nginx:80}
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
    volumes:
      - ./nginx/templates:/etc/nginx/templates
    depends_on:
      - go-service
    networks:
      - backend

networks:
  backend:
    external: true