services:

  go-service:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_service
    command: >
      sh -c "sleep 5 &&
             /app/main"
    env_file:
      - ./app.env
    networks:
      - common

  nginx:
    platform: linux/amd64
    image: nginx:latest
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - go-service
    networks:
      - common

  caddy:
    image: caddy
    container_name: caddy
    ports:
      - "8081:80"   # Change HTTP port for Caddy to 8081
      - "8443:443"  # Change HTTPS port for Caddy to 8443
      - "2019:2019"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - go-service
    networks:
      - common

networks:
  common: