apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "profiles.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-7"
    "helm.sh/hook-delete-policy": before-hook-creation

type: Opaque
stringData:
{{- include "common.dotenv.set" (dict "Files" .Files "filePath" .Values.envFileName $) }}