apiVersion: v1
kind: Secret
metadata:
  name: casbin
  labels:
    {{- include "profiles.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-7"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  model.conf: |
    {{ .Files.Get .Values.casbin.modelPath | b64enc | nindent 4 }}
  policy.csv: |
    {{ .Files.Get .Values.casbin.policyPath | b64enc | nindent 4 }}
