services:
  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: n00n3
      POSTGRES_DB: db.v2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "6500:5432"
    networks:
      - backend
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: rblbl@mail.ru
      PGADMIN_DEFAULT_PASSWORD: s0m30n3
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - backend

  backup:
    image: postgres:14
    container_name: postgres_backup
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: n00n3
      POSTGRES_DB: db.v2
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
    entrypoint: >
      /bin/sh -c "
      sleep 3;
      mkdir -p /backups &&
      while true; do
        set -x
        echo \"Starting backup...\"
        PGPASSWORD=$$POSTGRES_PASSWORD pg_dump -h $$POSTGRES_HOST -p $$POSTGRES_PORT -U $$POSTGRES_USER $$POSTGRES_DB > /backups/db_backup_$(date +\%Y\%m\%d_\%H\%M\%S).sql;
        echo \"Backup complete, sleeping\"
        sleep 86400;
      done"
    depends_on:
      - db
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    name: backend
  common: