annotations:
  category: Infrastructure
apiVersion: v2
appVersion: 1.0.0
description: A Library Helm Chart for grouping common logic between pimmer charts.
  This chart is not deployable by itself.
keywords:
- common
- helper
- template
- function
name: common
type: library
version: 1.0.0
